---
version: 1
enabled: true
comment_template_file: .stoat/comment.hbs
plugins:
  job_runtime:
    enabled: false
  static_hosting:
    video_preview:
      path: out/video.mp4
    gif_preview:
      path: out/video.gif
